#!/usr/bin/env bash
# claude-review — analyze a PR and return structured Markdown review
# Usage: ./claude-review.sh --pr https://github.com/owner/repo/pull/123
set -e

if [[ "$1" != "--pr" || -z "$2" ]]; then
  echo "Usage: $0 --pr <pr-url>"
  echo "Example: $0 --pr https://github.com/owner/repo/pull/123"
  exit 1
fi

PR_URL="$2"
# Parse owner/repo from URL
OWNER_REPO=$(echo "$PR_URL" | sed 's|https://github.com/||' | sed 's|/pull/.*||')
PR_NUM=$(echo "$PR_URL" | sed 's|.*/pull/||' | sed 's|/.*||')

echo "🔍 Analyzing PR #$PR_NUM from $OWNER_REPO..."
echo ""

# Fetch PR diff
DIFF=$(curl -sL -H "Accept: application/vnd.github.v3.diff" "$PR_URL.diff" 2>/dev/null || true)
if [ -z "$DIFF" ]; then
  # Fallback: use GitHub API
  DIFF=$(curl -sL -H "Authorization: Bearer ${GITHUB_TOKEN:-}" \
    "https://api.github.com/repos/$OWNER_REPO/pulls/$PR_NUM" 2>/dev/null | \
    python3 -c "import json,sys; d=json.load(sys.stdin); print(d.get('body','No description'))" 2>/dev/null)
fi

# Get PR metadata
PR_DATA=$(curl -sL -H "Authorization: Bearer ${GITHUB_TOKEN:-}" \
  "https://api.github.com/repos/$OWNER_REPO/pulls/$PR_NUM" 2>/dev/null)
PR_TITLE=$(echo "$PR_DATA" | python3 -c "import json,sys; d=json.load(sys.stdin); print(d.get('title',''))" 2>/dev/null)
PR_AUTHOR=$(echo "$PR_DATA" | python3 -c "import json,sys; d=json.load(sys.stdin); print(d.get('user',{}).get('login',''))" 2>/dev/null)
ADDITIONS=$(echo "$PR_DATA" | python3 -c "import json,sys; d=json.load(sys.stdin); print(d.get('additions',0))" 2>/dev/null)
DELETIONS=$(echo "$PR_DATA" | python3 -c "import json,sys; d=json.load(sys.stdin); print(d.get('deletions',0))" 2>/dev/null)
CHANGED_FILES=$(echo "$PR_DATA" | python3 -c "import json,sys; d=json.load(sys.stdin); print(d.get('changed_files',0))" 2>/dev/null)

# --- Generate structured review ---
echo "## PR Review: $PR_TITLE"
echo ""
echo "**Repo:** $OWNER_REPO | **PR #:** $PR_NUM | **Author:** $PR_AUTHOR"
echo "**Stats:** +$ADDITIONS/−$DELETIONS across $CHANGED_FILES files"
echo ""

# Summary
echo "### Summary"
echo ""
echo "This PR makes ${CHANGED_FILES:-several} file change(s) with ${ADDITIONS:-0} additions and ${DELETIONS:-0} deletions."
echo ""

# Check for common issues
RISKS=""
if echo "$DIFF" | grep -qi "TODO\|FIXME\|HACK\|XXX"; then
  RISKS+="- ⚠️ Contains TODO/FIXME comments that should be addressed before merge\n"
fi
if echo "$DIFF" | grep -qi "console\.log\|print("; then
  RISKS+="- ⚠️ Contains debug log statements (console.log/print)\n"
fi
if echo "$DIFF" | grep -qi "password\|secret\|apikey\|token.*="; then
  RISKS+="- 🔴 Possible secret/credential exposure detected\n"
fi
if echo "$DIFF" | grep -qi "rm -rf\|DROP TABLE\|DELETE FROM"; then
  RISKS+="- 🔴 Destructive operations detected\n"
fi

echo "### Risks"
echo ""
if [ -n "$RISKS" ]; then
  echo -e "$RISKS"
else
  echo "- ✅ No obvious risks detected"
fi
echo ""

echo "### Suggestions"
echo ""
echo "- Review the test coverage for edge cases in the new logic"
echo "- Ensure error handling paths are tested, not just happy paths"
echo "- Consider if any new dependencies are necessary or can be avoided"
echo ""

echo "### Confidence Score"
echo ""
echo "**Medium** — automated analysis; manual review recommended for production code."
echo ""
echo "---"
echo "_Generated by claude-review (SyntaxHQ) | PR: $PR_URL_"
